config/routes.rb
Rails.application.routes.draw do

  resources :sessions, only: [:new, :create, :destroy]

  get '/sign-in' => 'sessions#new'
  delete '/sign-out' => 'sessions#destroy'

  devise_for :admins
  resources :movies

  root 'static#home'

  get '/about' => 'static#about'

  get '/cat-pictures(/:number_of_cats)' => 'static#cats', as: :cat_pictures

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  validates_presence_of :title, :director
  validates :rating, :numericality => {:only_integer => true, :greater_than_or_equal_to => 0, :less_than_or_equal_to => 2015}
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

    def current_user
      User.find_by(id: session[:user_id])
    end
    helper_method :current_user

    def user_signed_in?
      !!current_user
    end
    helper_method :user_signed_in?

    def only_allow_signed_in_users
      unless user_signed_in?
        redirect_to sign_in_url, notice: 'You must sign in to access this part of the app.'
      end
    end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :only_allow_signed_in_users, except: [:index, :show]
  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:title, :director, :rating, :comments)
    end
end

app/controllers/recyclers_controller.rb
class RecyclersController < ApplicationController
  before_action :set_recycler, only: [:show, :edit, :update, :destroy]

  # GET /recyclers
  # GET /recyclers.json
  def index
    @recyclers = Recycler.all
  end

  # GET /recyclers/1
  # GET /recyclers/1.json
  def show
  end

  # GET /recyclers/new
  def new
    @recycler = Recycler.new
  end

  # GET /recyclers/1/edit
  def edit
  end

  # POST /recyclers
  # POST /recyclers.json
  def create
    @recycler = Recycler.new(recycler_params)

    respond_to do |format|
      if @recycler.save
        format.html { redirect_to @recycler, notice: 'Recycler was successfully created.' }
        format.json { render :show, status: :created, location: @recycler }
      else
        format.html { render :new }
        format.json { render json: @recycler.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recyclers/1
  # PATCH/PUT /recyclers/1.json
  def update
    respond_to do |format|
      if @recycler.update(recycler_params)
        format.html { redirect_to @recycler, notice: 'Recycler was successfully updated.' }
        format.json { render :show, status: :ok, location: @recycler }
      else
        format.html { render :edit }
        format.json { render json: @recycler.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recyclers/1
  # DELETE /recyclers/1.json
  def destroy
    @recycler.destroy
    respond_to do |format|
      format.html { redirect_to recyclers_url, notice: 'Recycler was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recycler
      @recycler = Recycler.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recycler_params
      params.require(:recycler).permit(:name, :phone, :email, :male, :female, :comments)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: 'Logged in!'
    else
      flash.alert = 'Invalid email/password combination. Please try again.'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Successfully signed out!'
  end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end

  def about
  end

  def cats
    @cats = CatAPI.new.get_images(results_per_page: params[:number_of_cats] || 1)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_helper.rb
module StaticHelper

  def current_date_time
    Time.now.strftime('%B %-d, %Y at %-l:%M%P')
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project 10</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <ul>
  <li><%= link_to 'Home', root_path %></li>
  <li><%= link_to 'About', about_path %></li>
  <li><%= link_to 'Cats', cat_pictures_path %></li>
  <li><%= link_to 'Movies', movies_path %></li>
</ul>
  
  <% flash.each do |type, message| %>
    <div class="<%= type %>">
      <p><%= message %></p>
    </div>
  <% end %>

  <% if user_signed_in? %>
    <li>Signed in in as <%= current_user.email %></li>
    <li><%= link_to "Sign Out", sign_out_path, method: :delete %></li>
  <% else %>
    <li><%= link_to "Sign In", sign_in_path %></li>
  <% end %>

<%= yield %>



</body>
</html>

app/views/movies/_form.html.erb
<%= form_for(@movie) do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :director %><br>
    <%= f.text_field :director %>
  </div>
  <div class="field">
    <%= f.label :rating %><br>
    <%= f.number_field :rating %>
  </div>
  <div class="field">
    <%= f.label :comments %><br>
    <%= f.text_area :comments %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Movies</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Director</th>
      <th>Year</th>
      <th>Comments</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= movie.title %></td>
        <td><%= movie.director %></td>
        <td><%= movie.rating %></td>
        <td><%= movie.comments %></td>
        <% if user_signed_in? %>
        <td><%= link_to 'Show', movie %></td>
        <% end %>
        <% if user_signed_in? %>
        <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
        <% end %>
        <% if user_signed_in? %>
        <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
  <% if user_signed_in? %>
    <%= link_to 'New Movie', new_movie_path %>
  <% end %>

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form' %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @movie.title %>
</p>

<p>
  <strong>Director:</strong>
  <%= @movie.director %>
</p>

<p>
  <strong>Year:</strong>
  <%= @movie.rating %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @movie.comments %>
</p>

<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %>